/**
 * @fileoverview ShEx-to-YAMA reverse import.
 *
 * Uses a simple regex-based parser to handle the common ShExC subset
 * generated by YAMA's ShEx exporter. Does not attempt to handle the
 * full ShEx grammar — just the patterns YAMA produces:
 *
 * ```shex
 * PREFIX prefix: <uri>
 * BASE <uri>
 *
 * <ShapeName> EXTRA a {
 *   a [ClassName] ;
 *   prefix:property xsd:datatype {m,n} ;
 *   prefix:property @<OtherShape> * ;
 *   prefix:property IRI + ;
 *   prefix:property LITERAL ? ;
 *   prefix:property ["val1" "val2"] ;
 *   prefix:property xsd:decimal //pattern// MinInclusive 0 MaxInclusive 100 ;
 * }
 * ```
 *
 * ShEx-to-YAMA mapping (inverse of {@link module:shex}):
 *
 * | ShExC element                  | YAMA element              |
 * |--------------------------------|---------------------------|
 * | Shape name `<name>`            | description               |
 * | `a [ClassName]`                | description.a             |
 * | Triple constraint predicate    | statement.property        |
 * | Datatype (e.g. `xsd:string`)  | statement.datatype        |
 * | `@<shapeName>`                 | statement.description     |
 * | `IRI`                          | statement.type = IRI      |
 * | `LITERAL`                      | statement.type = literal  |
 * | `BNODE`                        | statement.type = BNODE    |
 * | Cardinality `*`, `+`, `?`, `{m,n}` | statement.min/max    |
 * | Value set `["a" "b"]`          | statement.values          |
 * | `//pattern//`                  | statement.pattern         |
 * | `MinInclusive N`               | statement.facets.MinInclusive |
 * | `MaxInclusive N`               | statement.facets.MaxInclusive |
 * | `MinLength N`                  | statement.facets.MinLength |
 * | `MaxLength N`                  | statement.facets.MaxLength |
 *
 * @module from-shex
 * @see https://shex.io
 */

import { stringify as stringifyYaml } from "@std/yaml";
import { readInput } from "./io.js";

// ---------------------------------------------------------------------------
// Prefix / BASE parsing
// ---------------------------------------------------------------------------

/**
 * Extracts PREFIX declarations from ShExC source.
 *
 * @param {string} text - ShExC source text.
 * @returns {Object} Prefix-to-IRI map.
 */
function parsePrefixes(text) {
  const prefixes = {};
  const re = /^\s*PREFIX\s+(\w+):\s+<([^>]+)>/gmi;
  let m;
  while ((m = re.exec(text)) !== null) {
    prefixes[m[1]] = m[2];
  }
  return prefixes;
}

/**
 * Extracts BASE declaration from ShExC source.
 *
 * @param {string} text - ShExC source text.
 * @returns {string} Base IRI, or empty string.
 */
function parseBase(text) {
  const m = text.match(/^\s*BASE\s+<([^>]+)>/mi);
  return m ? m[1] : "";
}

// ---------------------------------------------------------------------------
// Cardinality parsing
// ---------------------------------------------------------------------------

/**
 * Parses a ShExC cardinality marker from the end of a constraint line.
 *
 * @param {string} cardStr - Cardinality string (e.g. "*", "+", "?", "{1,3}", "{2}").
 * @returns {{min?: number, max?: number}}
 */
function parseCardinality(cardStr) {
  if (!cardStr) return {};

  const trimmed = cardStr.trim();
  if (trimmed === "*") return { min: 0 };
  if (trimmed === "+") return { min: 1 };
  if (trimmed === "?") return { min: 0, max: 1 };

  // {n} or {m,n} or {m,}
  const rangeMatch = trimmed.match(/^\{(\d+)(?:,(\d*))?\}$/);
  if (rangeMatch) {
    const m = parseInt(rangeMatch[1], 10);
    if (rangeMatch[2] === undefined) {
      // {n} — exact
      return { min: m, max: m };
    }
    if (rangeMatch[2] === "") {
      // {m,} — unbounded
      return { min: m };
    }
    return { min: m, max: parseInt(rangeMatch[2], 10) };
  }

  return {};
}

// ---------------------------------------------------------------------------
// Statement key generation
// ---------------------------------------------------------------------------

/**
 * Generates a statement key from a property term.
 *
 * @param {string} property - Prefixed term (e.g. "foaf:name") or keyword.
 * @param {Set<string>} usedKeys
 * @returns {string}
 */
function toStatementKey(property, usedKeys) {
  let local = property;

  // Extract local part from prefixed term
  const colonIdx = property.indexOf(":");
  if (colonIdx >= 0) {
    local = property.slice(colonIdx + 1);
  }

  // Extract from full IRI
  const hashIdx = local.lastIndexOf("#");
  if (hashIdx >= 0) local = local.slice(hashIdx + 1);
  const slashIdx = local.lastIndexOf("/");
  if (slashIdx >= 0) local = local.slice(slashIdx + 1);

  // Ensure camelCase start
  let key = local.charAt(0).toLowerCase() + local.slice(1);

  // Deduplicate
  if (usedKeys.has(key)) {
    let suffix = 2;
    while (usedKeys.has(`${key}${suffix}`)) suffix++;
    key = `${key}${suffix}`;
  }

  usedKeys.add(key);
  return key;
}

// ---------------------------------------------------------------------------
// Triple constraint parser
// ---------------------------------------------------------------------------

/**
 * Parses a single triple constraint line from inside a shape body.
 *
 * Handles these forms:
 *   a [ClassName]
 *   prefix:prop xsd:datatype {m,n}
 *   prefix:prop @<ShapeName> *
 *   prefix:prop IRI +
 *   prefix:prop LITERAL ?
 *   prefix:prop BNODE
 *   prefix:prop ["val1" "val2"]
 *   prefix:prop xsd:decimal //pattern// MinInclusive 0 MaxInclusive 100
 *
 * @param {string} line - Trimmed constraint line (without trailing ; or })
 * @returns {Object|null} Parsed statement object, or null if unparseable.
 */
function parseTripleConstraint(line) {
  if (!line.trim()) return null;

  // Handle `a [ClassName]` — rdf:type constraint
  const typeMatch = line.match(/^a\s+\[([^\]]+)\]/);
  if (typeMatch) {
    return { _isTypeConstraint: true, class: typeMatch[1].trim() };
  }

  // General triple constraint: predicate followed by node constraint
  // predicate is either a prefixed term (prefix:local) or <iri>
  const predMatch = line.match(/^(<[^>]+>|[\w]+:[\w]+)\s+(.*)/);
  if (!predMatch) return null;

  let property = predMatch[1];
  let rest = predMatch[2].trim();

  // Strip angle brackets from <iri>
  if (property.startsWith("<") && property.endsWith(">")) {
    property = property.slice(1, -1);
  }

  const stmt = { property };

  // Extract cardinality from the end
  const cardMatch = rest.match(/\s+([*+?]|\{\d+(?:,\d*)?\})\s*$/);
  let cardinality = "";
  if (cardMatch) {
    cardinality = cardMatch[1];
    rest = rest.slice(0, rest.length - cardMatch[0].length).trim();
  }

  const card = parseCardinality(cardinality);
  if (card.min !== undefined) stmt.min = card.min;
  if (card.max !== undefined) stmt.max = card.max;

  // Parse the remaining node constraint

  // Shape reference: @<shapeName>
  const shapeRefMatch = rest.match(/^@<([^>]+)>(.*)/);
  if (shapeRefMatch) {
    stmt.description = shapeRefMatch[1];
    rest = shapeRefMatch[2].trim();
  }
  // Value set: ["val1" "val2"]
  else if (rest.startsWith("[")) {
    const closeIdx = rest.indexOf("]");
    if (closeIdx >= 0) {
      const valueContent = rest.slice(1, closeIdx);
      const values = [];
      const valRe = /"([^"]*)"/g;
      let vm;
      while ((vm = valRe.exec(valueContent)) !== null) {
        values.push(vm[1]);
      }
      if (values.length > 0) stmt.values = values;
      rest = rest.slice(closeIdx + 1).trim();
    }
  }
  // Node kind: IRI, LITERAL, BNODE, NONLITERAL
  else if (/^(IRI|LITERAL|BNODE|NONLITERAL)\b/i.test(rest)) {
    const nkMatch = rest.match(/^(IRI|LITERAL|BNODE|NONLITERAL)\b(.*)/i);
    if (nkMatch) {
      const nk = nkMatch[1].toUpperCase();
      if (nk === "IRI") stmt.type = "IRI";
      else if (nk === "LITERAL") stmt.type = "literal";
      else if (nk === "BNODE") stmt.type = "BNODE";
      else if (nk === "NONLITERAL") stmt.type = "IRI";
      rest = nkMatch[2].trim();
    }
  }
  // Datatype: prefix:localName or <iri>
  else {
    const dtMatch = rest.match(/^(<[^>]+>|[\w]+:[\w]+)(.*)/);
    if (dtMatch) {
      let dt = dtMatch[1];
      if (dt.startsWith("<") && dt.endsWith(">")) dt = dt.slice(1, -1);
      stmt.datatype = dt;
      rest = dtMatch[2].trim();
    }
  }

  // Parse remaining facets and pattern from `rest`

  // Pattern: //pattern//
  const patternMatch = rest.match(/\/\/([^/]+)\/\//);
  if (patternMatch) {
    stmt.pattern = patternMatch[1];
    rest = rest.replace(/\/\/[^/]+\/\//, "").trim();
  }

  // Numeric/string facets
  const facets = {};
  const facetNames = [
    "MinInclusive", "MaxInclusive", "MinExclusive", "MaxExclusive",
    "MinLength", "MaxLength", "TotalDigits", "FractionDigits", "Length",
  ];

  for (const facetName of facetNames) {
    const facetRe = new RegExp(`${facetName}\\s+([\\d.+-]+)`, "i");
    const fm = rest.match(facetRe);
    if (fm) {
      facets[facetName] = Number(fm[1]);
    }
  }

  if (Object.keys(facets).length > 0) stmt.facets = facets;

  return stmt;
}

// ---------------------------------------------------------------------------
// Shape parser
// ---------------------------------------------------------------------------

/**
 * Parses all shape definitions from a ShExC source string.
 *
 * @param {string} text - Full ShExC source.
 * @param {Object} _prefixes - Prefix-to-IRI map (reserved for future use).
 * @param {string} _base - Base IRI (reserved for future use).
 * @returns {Object} descriptions map.
 */
function parseShapes(text, _prefixes, _base) {
  const descriptions = {};

  // Remove comments and PREFIX/BASE lines for shape parsing
  const cleaned = text
    .split("\n")
    .filter((line) => {
      const trimmed = line.trim();
      return !trimmed.startsWith("#") &&
             !trimmed.toUpperCase().startsWith("PREFIX ") &&
             !trimmed.toUpperCase().startsWith("BASE ");
    })
    .join("\n");

  // Match shape blocks: <name> (EXTRA a)? { ... }
  // Use a manual brace-counting approach for robustness
  const shapeStartRe = /<([^>]+)>\s*(?:EXTRA\s+a\s*)?\{/g;
  let match;

  while ((match = shapeStartRe.exec(cleaned)) !== null) {
    const shapeName = match[1];
    const bodyStart = match.index + match[0].length;

    // Find matching closing brace
    let depth = 1;
    let i = bodyStart;
    while (i < cleaned.length && depth > 0) {
      if (cleaned[i] === "{") depth++;
      else if (cleaned[i] === "}") depth--;
      i++;
    }

    const body = cleaned.slice(bodyStart, i - 1).trim();

    // Split body into individual triple constraints on ; boundaries
    // Need to be careful not to split inside value sets [...]
    const constraints = splitConstraints(body);

    const desc = {};
    const statements = {};
    const usedKeys = new Set();

    for (const constraint of constraints) {
      const parsed = parseTripleConstraint(constraint.trim());
      if (!parsed) continue;

      if (parsed._isTypeConstraint) {
        // `a [ClassName]` -> description.a
        desc.a = parsed.class;
        continue;
      }

      const key = toStatementKey(parsed.property, usedKeys);
      delete parsed._isTypeConstraint;
      statements[key] = parsed;
    }

    if (Object.keys(statements).length > 0) {
      desc.statements = statements;
    }

    descriptions[shapeName] = desc;
  }

  return descriptions;
}

/**
 * Splits a shape body into individual triple constraints,
 * respecting brackets (value sets) and braces (cardinality).
 *
 * @param {string} body - Shape body content between { and }.
 * @returns {string[]} Array of individual constraint strings.
 */
function splitConstraints(body) {
  const constraints = [];
  let current = "";
  let bracketDepth = 0;
  let braceDepth = 0;

  for (let i = 0; i < body.length; i++) {
    const ch = body[i];

    if (ch === "[") bracketDepth++;
    else if (ch === "]") bracketDepth--;
    else if (ch === "{") braceDepth++;
    else if (ch === "}") braceDepth--;

    if (ch === ";" && bracketDepth === 0 && braceDepth === 0) {
      if (current.trim()) constraints.push(current.trim());
      current = "";
    } else {
      current += ch;
    }
  }

  if (current.trim()) constraints.push(current.trim());
  return constraints;
}

// ---------------------------------------------------------------------------
// Main converter
// ---------------------------------------------------------------------------

/**
 * Parses ShExC source text and builds a YAMA document.
 *
 * @param {string} text - ShExC source text.
 * @returns {Object} YAMA document.
 */
function parseShExToYama(text) {
  const prefixes = parsePrefixes(text);
  const base = parseBase(text);
  const descriptions = parseShapes(text, prefixes, base);

  const doc = {};
  if (base) doc.base = base;

  // Build namespace map
  const namespaces = {};
  for (const [prefix, uri] of Object.entries(prefixes)) {
    namespaces[prefix] = uri;
  }
  if (Object.keys(namespaces).length > 0) doc.namespaces = namespaces;

  doc.descriptions = descriptions;
  return doc;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Imports a ShEx file and converts it to YAMA YAML.
 *
 * @param {string} file     - Path to the ShEx input file.
 * @param {string} [output] - Output file path; stdout if omitted.
 * @returns {Promise<void>}
 */
export async function importShEx(file, output) {
  const text = await readInput(file);
  const doc = parseShExToYama(text);
  const yaml = stringifyYaml(doc, { lineWidth: -1 });

  if (output) {
    Deno.writeTextFileSync(output, yaml);
    console.error(`Written to ${output}`);
  } else {
    console.log(yaml);
  }
}
