/**
 * @fileoverview ShEx-to-YAMA reverse import.
 *
 * Uses a simple regex-based parser to handle the common ShExC subset
 * generated by YAMA's ShEx exporter. Does not attempt to handle the
 * full ShEx grammar — just the patterns YAMA produces:
 *
 * ```shex
 * PREFIX prefix: <uri>
 * PREFIX : <uri>
 * BASE <uri>
 *
 * <ShapeName> EXTRA a CLOSED {
 *   a [ClassName] ;
 *   prefix:property xsd:datatype {m,n} ;
 *   prefix:property @<OtherShape> * ;
 *   prefix:property IRI + ;
 *   prefix:property LITERAL ? ;
 *   prefix:property ["val1" "val2"] ;
 *   prefix:property [ex:a ex:b] ;
 *   prefix:property xsd:decimal /pattern/ MinInclusive 0 MaxInclusive 100 ;
 * }
 * ```
 *
 * ShEx-to-YAMA mapping (inverse of {@link module:shex}):
 *
 * | ShExC element                  | YAMA element              |
 * |--------------------------------|---------------------------|
 * | Shape name `<name>`            | description               |
 * | `CLOSED` qualifier             | description.closed = true |
 * | `a [ClassName]`                | description.a             |
 * | Triple constraint predicate    | statement.property        |
 * | Datatype (e.g. `xsd:string`)  | statement.datatype        |
 * | `@<shapeName>`                 | statement.description     |
 * | `IRI`                          | statement.type = IRI      |
 * | `LITERAL`                      | statement.type = literal  |
 * | `BNODE`                        | statement.type = BNODE    |
 * | Cardinality `*`, `+`, `?`, `{m,n}` | statement.min/max    |
 * | Value set `["a" "b"]`          | statement.values          |
 * | Value set `[ex:a <iri>]`       | statement.values (IRIs)   |
 * | Value set `[ex:~]` (IRI stem)  | statement.inScheme        |
 * | Value set `[@en @ja]`          | statement.languageTag     |
 * | `/pattern/` or legacy `//pattern//` | statement.pattern    |
 * | `MinInclusive N`               | statement.facets.MinInclusive |
 * | `MaxInclusive N`               | statement.facets.MaxInclusive |
 * | `MinLength N`                  | statement.facets.MinLength |
 * | `MaxLength N`                  | statement.facets.MaxLength |
 *
 * Prefixed names accept the PN_LOCAL range seen in the wild — local
 * names with `-` and `.` (e.g. `bf:title-proper`) and the empty
 * default prefix (`:name`) — not just the `\w` subset.
 *
 * Triple-constraint lines matching none of the patterns above are not
 * imported; each dropped line produces a console warning naming the
 * shape, mirroring how {@link module:from-shacl} reports constructs
 * it cannot express.
 *
 * @module from-shex
 * @see https://shex.io
 */

import { stringify as stringifyYaml } from "@std/yaml";
import { readInput, statusLog } from "./io.js";

// ---------------------------------------------------------------------------
// Shared token patterns
// ---------------------------------------------------------------------------

/**
 * Regex source for a ShExC prefixed name (PNAME_LN, lenient).
 *
 * Prefix: optional (the default prefix `:name` is valid), starting
 * with a letter, then letters/digits/`_`/`.`/`-`. Local: letters,
 * digits, `_`, `.`, `-`. Broader than `\w+:\w+`, which silently
 * dropped properties like `bf:title-proper` or `ex:has.part`.
 *
 * @type {string}
 */
const PNAME_SRC = "(?:[A-Za-z][\\w.-]*)?:[\\w-][\\w.-]*";

// ---------------------------------------------------------------------------
// Prefix / BASE parsing
// ---------------------------------------------------------------------------

/**
 * Extracts PREFIX declarations from ShExC source.
 *
 * Accepts the empty default prefix (`PREFIX : <…>`, stored under the
 * key `""`) and prefixes containing `-` or `.`.
 *
 * @param {string} text - ShExC source text.
 * @returns {Object} Prefix-to-IRI map.
 */
function parsePrefixes(text) {
  const prefixes = {};
  const re = /^\s*PREFIX\s+([A-Za-z][\w.-]*)?:\s*<([^>]+)>/gmi;
  let m;
  while ((m = re.exec(text)) !== null) {
    prefixes[m[1] ?? ""] = m[2];
  }
  return prefixes;
}

/**
 * Extracts BASE declaration from ShExC source.
 *
 * @param {string} text - ShExC source text.
 * @returns {string} Base IRI, or empty string.
 */
function parseBase(text) {
  const m = text.match(/^\s*BASE\s+<([^>]+)>/mi);
  return m ? m[1] : "";
}

// ---------------------------------------------------------------------------
// Cardinality parsing
// ---------------------------------------------------------------------------

/**
 * Parses a ShExC cardinality marker from the end of a constraint line.
 *
 * @param {string} cardStr - Cardinality string (e.g. "*", "+", "?", "{1,3}", "{2}").
 * @returns {{min?: number, max?: number}}
 */
function parseCardinality(cardStr) {
  if (!cardStr) return {};

  const trimmed = cardStr.trim();
  if (trimmed === "*") return { min: 0 };
  if (trimmed === "+") return { min: 1 };
  if (trimmed === "?") return { min: 0, max: 1 };

  // {n} or {m,n} or {m,}
  const rangeMatch = trimmed.match(/^\{(\d+)(?:,(\d*))?\}$/);
  if (rangeMatch) {
    const m = parseInt(rangeMatch[1], 10);
    if (rangeMatch[2] === undefined) {
      // {n} — exact
      return { min: m, max: m };
    }
    if (rangeMatch[2] === "") {
      // {m,} — unbounded
      return { min: m };
    }
    return { min: m, max: parseInt(rangeMatch[2], 10) };
  }

  return {};
}

// ---------------------------------------------------------------------------
// Statement key generation
// ---------------------------------------------------------------------------

/**
 * Generates a statement key from a property term.
 *
 * @param {string} property - Prefixed term (e.g. "foaf:name") or keyword.
 * @param {Set<string>} usedKeys
 * @returns {string}
 */
function toStatementKey(property, usedKeys) {
  let local = property;

  // Extract local part from prefixed term
  const colonIdx = property.indexOf(":");
  if (colonIdx >= 0) {
    local = property.slice(colonIdx + 1);
  }

  // Extract from full IRI
  const hashIdx = local.lastIndexOf("#");
  if (hashIdx >= 0) local = local.slice(hashIdx + 1);
  const slashIdx = local.lastIndexOf("/");
  if (slashIdx >= 0) local = local.slice(slashIdx + 1);

  // Ensure camelCase start
  let key = local.charAt(0).toLowerCase() + local.slice(1);

  // Deduplicate
  if (usedKeys.has(key)) {
    let suffix = 2;
    while (usedKeys.has(`${key}${suffix}`)) suffix++;
    key = `${key}${suffix}`;
  }

  usedKeys.add(key);
  return key;
}

// ---------------------------------------------------------------------------
// Triple constraint parser
// ---------------------------------------------------------------------------

/**
 * Parses a single triple constraint line from inside a shape body.
 *
 * Handles these forms:
 *   a [ClassName]
 *   prefix:prop xsd:datatype {m,n}
 *   prefix:prop @<ShapeName> *
 *   prefix:prop IRI +
 *   prefix:prop LITERAL ?
 *   prefix:prop BNODE
 *   prefix:prop ["val1" "val2"]
 *   prefix:prop xsd:decimal //pattern// MinInclusive 0 MaxInclusive 100
 *
 * @param {string} line - Trimmed constraint line (without trailing ; or })
 * @returns {Object|null} Parsed statement object, or null if unparseable.
 */
function parseTripleConstraint(line) {
  if (!line.trim()) return null;

  // Handle `a [ClassName]` — rdf:type constraint
  const typeMatch = line.match(/^a\s+\[([^\]]+)\]/);
  if (typeMatch) {
    return { _isTypeConstraint: true, class: typeMatch[1].trim() };
  }

  // General triple constraint: predicate followed by node constraint
  // predicate is either a prefixed term (prefix:local, default-prefix
  // :local, hyphens/dots allowed) or <iri>
  const predMatch = line.match(
    new RegExp(`^(<[^>]+>|${PNAME_SRC})\\s+(.*)`, "s"),
  );
  if (!predMatch) return null;

  let property = predMatch[1];
  let rest = predMatch[2].trim();

  // Strip angle brackets from <iri>
  if (property.startsWith("<") && property.endsWith(">")) {
    property = property.slice(1, -1);
  }

  const stmt = { property };

  // Extract cardinality from the end
  const cardMatch = rest.match(/\s+([*+?]|\{\d+(?:,\d*)?\})\s*$/);
  let cardinality = "";
  if (cardMatch) {
    cardinality = cardMatch[1];
    rest = rest.slice(0, rest.length - cardMatch[0].length).trim();
  }

  const card = parseCardinality(cardinality);
  if (card.min !== undefined) stmt.min = card.min;
  if (card.max !== undefined) stmt.max = card.max;

  // Parse the remaining node constraint

  // Multi-shape disjunction: (@<A> OR @<B> OR ...)
  // This extended form is emitted by shex.js for multi-ref statements;
  // strict ShExC would use a group expression but we keep the serialiser
  // symmetric by parsing the same form back.
  const disjMatch = rest.match(/^\(\s*((?:@<[^>]+>\s*OR\s*)+@<[^>]+>)\s*\)(.*)/);
  if (disjMatch) {
    const refs = Array.from(disjMatch[1].matchAll(/@<([^>]+)>/g)).map((m) => m[1]);
    stmt.description = refs.length === 1 ? refs[0] : refs;
    rest = disjMatch[2].trim();
  }
  // Multi-datatype disjunction: (xsd:gYear OR xsd:gYearMonth OR xsd:date)
  // Mirrors what shex.js emits for multi-datatype statements. The
  // group admits only PNAME tokens separated by OR; a parenthesised
  // constraint containing anything else is unrecognised, and the whole
  // line falls through to the dropped-line warning in parseShapes.
  else if (rest.startsWith("(")) {
    const dtMatch = rest.match(
      new RegExp(
        `^\\(\\s*(${PNAME_SRC}(?:\\s+OR\\s+${PNAME_SRC})+)\\s*\\)(.*)`,
        "s",
      ),
    );
    if (!dtMatch) return null;
    const dts = dtMatch[1].split(/\s+OR\s+/).map((s) => s.trim());
    stmt.datatype = dts.length === 1 ? dts[0] : dts;
    rest = dtMatch[2].trim();
  }
  // Shape reference: @<shapeName>
  else if (/^@<[^>]+>/.test(rest)) {
    const shapeRefMatch = rest.match(/^@<([^>]+)>(.*)/);
    if (shapeRefMatch) {
      stmt.description = shapeRefMatch[1];
      rest = shapeRefMatch[2].trim();
    }
  }
  // Value set: ["val1" "val2"], [ex:a <http://…>], [ex:~] (IRI stem),
  // [@en @ja] (language tags). Members may mix; quoted strings become
  // literal values, IRIs/CURIEs become IRI values, `~`-suffixed stems
  // become inScheme entries, and `@lang` tokens become languageTag.
  else if (rest.startsWith("[")) {
    const closeIdx = rest.indexOf("]");
    if (closeIdx >= 0) {
      const valueContent = rest.slice(1, closeIdx);
      const values = [];
      const schemes = [];
      const langs = [];
      let sawIri = false;
      const tokenRe = /"((?:[^"\\]|\\.)*)"|<([^>]+)>(~)?|@([A-Za-z0-9-]+)|([^\s\]]+)/g;
      let tm;
      while ((tm = tokenRe.exec(valueContent)) !== null) {
        if (tm[1] !== undefined) {
          // Quoted literal — unescape \" and \\
          values.push(tm[1].replace(/\\(["\\])/g, "$1"));
        } else if (tm[2] !== undefined) {
          sawIri = true;
          if (tm[3]) schemes.push(tm[2]);
          else values.push(tm[2]);
        } else if (tm[4] !== undefined) {
          langs.push(tm[4]);
        } else if (tm[5]) {
          sawIri = true;
          const tok = tm[5];
          // `prefix:~` is an IRI stem; bare CURIEs are IRI members.
          if (tok.endsWith("~")) schemes.push(tok.slice(0, -1));
          else values.push(tok);
        }
      }
      if (langs.length > 0) stmt.languageTag = langs;
      if (schemes.length > 0) {
        stmt.inScheme = schemes.length === 1 ? schemes[0] : schemes;
      }
      if (values.length > 0) stmt.values = values;
      // IRI members imply an IRI-typed statement, matching what the
      // shex.js generator collapses into the value set.
      if (sawIri && !stmt.type) stmt.type = "IRI";
      rest = rest.slice(closeIdx + 1).trim();
    }
  }
  // Node kind: IRI, LITERAL, BNODE, NONLITERAL
  else if (/^(IRI|LITERAL|BNODE|NONLITERAL)\b/i.test(rest)) {
    const nkMatch = rest.match(/^(IRI|LITERAL|BNODE|NONLITERAL)\b(.*)/i);
    if (nkMatch) {
      const nk = nkMatch[1].toUpperCase();
      if (nk === "IRI") stmt.type = "IRI";
      else if (nk === "LITERAL") stmt.type = "literal";
      else if (nk === "BNODE") stmt.type = "BNODE";
      else if (nk === "NONLITERAL") stmt.type = "IRI";
      rest = nkMatch[2].trim();
    }
  }
  // Datatype: prefix:localName or <iri>
  else {
    const dtMatch = rest.match(new RegExp(`^(<[^>]+>|${PNAME_SRC})(.*)`, "s"));
    if (dtMatch) {
      let dt = dtMatch[1];
      if (dt.startsWith("<") && dt.endsWith(">")) dt = dt.slice(1, -1);
      stmt.datatype = dt;
      rest = dtMatch[2].trim();
    }
  }

  // Parse remaining facets and pattern from `rest`

  // Pattern: valid ShExC uses single slashes with `\/` escapes
  // (`/pat\/tern/`); the legacy yama-cli form `//pattern//` is still
  // accepted for backward compatibility.
  const legacyPattern = rest.match(/\/\/([^/]+)\/\//);
  if (legacyPattern) {
    stmt.pattern = legacyPattern[1];
    rest = rest.replace(legacyPattern[0], "").trim();
  } else {
    const patternMatch = rest.match(/\/((?:[^/\\\n]|\\.)+)\//);
    if (patternMatch) {
      // Unescape only the slash escapes the emitter added; other
      // regex escapes (\d, \., …) pass through untouched.
      stmt.pattern = patternMatch[1].replace(/\\\//g, "/");
      rest = rest.replace(patternMatch[0], "").trim();
    }
  }

  // Numeric/string facets
  const facets = {};
  const facetNames = [
    "MinInclusive", "MaxInclusive", "MinExclusive", "MaxExclusive",
    "MinLength", "MaxLength", "TotalDigits", "FractionDigits", "Length",
  ];

  for (const facetName of facetNames) {
    const facetRe = new RegExp(`${facetName}\\s+([\\d.+-]+)`, "i");
    const fm = rest.match(facetRe);
    if (fm) {
      facets[facetName] = Number(fm[1]);
    }
  }

  if (Object.keys(facets).length > 0) stmt.facets = facets;

  return stmt;
}

// ---------------------------------------------------------------------------
// Shape parser
// ---------------------------------------------------------------------------

/**
 * Parses all shape definitions from a ShExC source string.
 *
 * @param {string} text - Full ShExC source.
 * @param {Object} _prefixes - Prefix-to-IRI map (reserved for future use).
 * @param {string} _base - Base IRI (reserved for future use).
 * @returns {Object} descriptions map.
 */
function parseShapes(text, _prefixes, _base) {
  const descriptions = {};

  // Remove comments and PREFIX/BASE lines for shape parsing
  const cleaned = text
    .split("\n")
    .filter((line) => {
      const trimmed = line.trim();
      return !trimmed.startsWith("#") &&
             !trimmed.toUpperCase().startsWith("PREFIX ") &&
             !trimmed.toUpperCase().startsWith("BASE ");
    })
    .join("\n");

  // Match shape blocks: <name> (EXTRA a)? (CLOSED)? { ... }
  // Use a manual brace-counting approach for robustness
  const shapeStartRe = /<([^>]+)>((?:\s+(?:EXTRA\s+a|CLOSED))*)\s*\{/g;
  let match;

  while ((match = shapeStartRe.exec(cleaned)) !== null) {
    const shapeName = match[1];
    const qualifiers = match[2] || "";
    const bodyStart = match.index + match[0].length;

    // Find matching closing brace
    let depth = 1;
    let i = bodyStart;
    while (i < cleaned.length && depth > 0) {
      if (cleaned[i] === "{") depth++;
      else if (cleaned[i] === "}") depth--;
      i++;
    }

    const body = cleaned.slice(bodyStart, i - 1).trim();

    // Split body into individual triple constraints on ; boundaries
    // Need to be careful not to split inside value sets [...]
    const constraints = splitConstraints(body);

    const desc = {};
    const statements = {};
    const usedKeys = new Set();

    // CLOSED qualifier → closed: true (shapes reject undeclared
    // properties).
    if (/\bCLOSED\b/.test(qualifiers)) desc.closed = true;

    for (const constraint of constraints) {
      const line = constraint.trim();
      const parsed = parseTripleConstraint(line);
      if (!parsed) {
        // Mirror from-shacl.js: never drop input silently. Comments
        // survive splitConstraints when they follow a `;` on the same
        // line, so they are excluded here.
        if (line && !line.startsWith("#")) {
          console.warn(
            `Warning: shape <${shapeName}>: unrecognised constraint "${
              line.replace(/\s+/g, " ")
            }" — dropped.`,
          );
        }
        continue;
      }

      if (parsed._isTypeConstraint) {
        // `a [ClassName]` -> description.a
        desc.a = parsed.class;
        continue;
      }

      const key = toStatementKey(parsed.property, usedKeys);
      delete parsed._isTypeConstraint;
      statements[key] = parsed;
    }

    if (Object.keys(statements).length > 0) {
      desc.statements = statements;
    }

    descriptions[shapeName] = desc;
  }

  return descriptions;
}

/**
 * Splits a shape body into individual triple constraints,
 * respecting brackets (value sets) and braces (cardinality).
 *
 * @param {string} body - Shape body content between { and }.
 * @returns {string[]} Array of individual constraint strings.
 */
function splitConstraints(body) {
  const constraints = [];
  let current = "";
  let bracketDepth = 0;
  let braceDepth = 0;

  for (let i = 0; i < body.length; i++) {
    const ch = body[i];

    if (ch === "[") bracketDepth++;
    else if (ch === "]") bracketDepth--;
    else if (ch === "{") braceDepth++;
    else if (ch === "}") braceDepth--;

    if (ch === ";" && bracketDepth === 0 && braceDepth === 0) {
      if (current.trim()) constraints.push(current.trim());
      current = "";
    } else {
      current += ch;
    }
  }

  if (current.trim()) constraints.push(current.trim());
  return constraints;
}

// ---------------------------------------------------------------------------
// Main converter
// ---------------------------------------------------------------------------

/**
 * Parses ShExC source text and builds a YAMA document.
 *
 * @param {string} text - ShExC source text.
 * @returns {Object} YAMA document.
 */
function parseShExToYama(text) {
  const prefixes = parsePrefixes(text);
  let base = parseBase(text);
  const descriptions = parseShapes(text, prefixes, base);

  // The generator emits shape names and @<...> refs as full IRIs with
  // no BASE directive. Without stripping, description keys would be
  // full IRIs (e.g. "http://example.org/ap#Person") instead of local
  // names. Derive a common base from the shape IRIs (when none was
  // declared) and strip it from both keys and refs so the import
  // round-trips to clean local names.
  if (!base) base = deriveCommonBase(Object.keys(descriptions));
  const stripped = base ? stripBaseFromShapes(descriptions, base) : descriptions;

  const doc = {};
  if (base) doc.base = base;

  // Build namespace map
  const namespaces = {};
  for (const [prefix, uri] of Object.entries(prefixes)) {
    namespaces[prefix] = uri;
  }
  if (Object.keys(namespaces).length > 0) doc.namespaces = namespaces;

  doc.descriptions = stripped;
  return doc;
}

/**
 * Derives a common base IRI shared by every shape name, up to the last
 * `/` or `#`. Returns "" when the names don't share a prefix (or aren't
 * IRIs), mirroring from-shacl.js's base derivation.
 *
 * @param {string[]} shapeNames - Full shape IRIs (description keys).
 * @returns {string} The common base, or "".
 */
function deriveCommonBase(shapeNames) {
  const iris = shapeNames.filter((n) => /^(https?|urn):/.test(n));
  if (iris.length === 0) return "";
  const first = iris[0];
  const lastSep = Math.max(first.lastIndexOf("/"), first.lastIndexOf("#"));
  if (lastSep <= 0) return "";
  const candidate = first.slice(0, lastSep + 1);
  return iris.every((iri) => iri.startsWith(candidate)) ? candidate : "";
}

/**
 * Strips a base IRI from description keys and from every `description`
 * reference that points at a same-base shape, leaving clean local
 * names. Refs to IRIs outside the base are left untouched.
 *
 * @param {Object} descriptions - Map of shape-IRI → description.
 * @param {string} base - The base IRI to strip.
 * @returns {Object} A new descriptions map keyed by local name.
 */
function stripBaseFromShapes(descriptions, base) {
  const strip = (iri) =>
    typeof iri === "string" && iri.startsWith(base) ? iri.slice(base.length) : iri;
  const out = {};
  for (const [key, desc] of Object.entries(descriptions)) {
    for (const stmt of Object.values(desc.statements || {})) {
      if (stmt.description === undefined) continue;
      stmt.description = Array.isArray(stmt.description)
        ? stmt.description.map(strip)
        : strip(stmt.description);
    }
    out[strip(key)] = desc;
  }
  return out;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Imports a ShEx file and converts it to YAMA YAML.
 *
 * @param {string} file     - Path to the ShEx input file.
 * @param {string} [output] - Output file path; stdout if omitted.
 * @returns {Promise<void>}
 */
export async function importShEx(file, output) {
  const text = await readInput(file);
  const doc = parseShExToYama(text);
  const yaml = stringifyYaml(doc, { lineWidth: -1 });

  if (output) {
    Deno.writeTextFileSync(output, yaml);
    statusLog(`Written to ${output}`);
  } else {
    console.log(yaml);
  }
}

export { parseShExToYama };
